name: CI/CD Docker Build & Deploy Backend

on:
  push:
    branches:
      - 'main'

defaults:
  run: 
    working-directory: ./backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU (Backend)
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx (Backend)
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub (Backend)
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (Backend)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          push: true
          tags: jjveldscholten/slimmemeter-backend:latest
